### ISSUE TITLE
[FEATURE] Extend the benchmarks and run them automatically

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#349] opened 2020-12-06 10:24 UTC
We have a small set of benchmarks in [apalache-tests](https://github.com/informalsystems/apalache-tests/issues).

Our usage of these benchmarks has the following problems:

  - we run them rarely, usually, before a release
  - we should run these benchmarks automatically every week, e.g., on Saturday (a single run may take 1-2 days)
  - we should extend these benchmarks with the [Informal specifications](https://github.com/tendermint/spec/tree/master/rust-spec/), as this is how we are currently bringing value with this project at [Informal](https://informal.systems/).

If we did that, we would have detected the breaking commit 57d95aefcbcbf992079a662cd54fd970ea8e7ae7 from November 19 early.

@shonfeder what do you think about this?

**Comment by shonfeder** [comment] 2020-12-07 13:55
The "run automatically" part overlaps with #182 iiuc.

I'm uncertain whether dumping the informal specifications into our benchmarks is a good idea.

- It seems like the logic here would be to test for regressions. But regression tests should be focused and specific, IMO, and they should be a distinct phase from bench marking.
- How will we make sure the specs stay in sync if they change in their source repos?
- What if they add significant overtime to our benchmarks but don't exercise useful code paths?
- What if they fail due to incorrect specs rather than an error with Apalache? Then we have to manually report the break upstream, but this opens up opportunity for failure to report etc.

Instead, I suggest:

1. We carefully extract regression tests for any failing cases we discover and incorporate those into our integration tests.
2. We create a github action to make it trivial to integrate apalache into the CI process of client code, and add that into the CI of repositories where the specs live.
  - This address internal value delivery more cleanly and directly than dumping specs into our benchmarks.

**Comment by konnov** [comment] 2020-12-07 14:27
Well, we have unit tests and integration tests. However, it happens every now and then that the realistic benchmarks fail after several months of work. There are two reasons for running the Informal specs: we detect early when they stop working; and we detect early if our improvements slow down the benchmarks that are interesting to us. I don't think it will work with github actions, if the experiments are running for 1-2 days, right?

**Comment by lemmy** [comment] 2020-12-07 16:18
https://docs.github.com/en/free-pro-team@latest/actions/reference/usage-limits-billing-and-administration#usage-limits

**Comment by shonfeder** [comment] 2020-12-10 00:37
Do we really need to run multi-day benchmarks? Does this add value to metrics we want to record?

**Comment by konnov** [comment] 2020-12-10 07:54
Yes. The performance drop can be clearly seen on longer benchmarks. Also, some of them fail only after hours of running.

**Comment by konnov** [comment] 2020-12-11 15:26
I would say that the tests in [apalache-tests](https://github.com/informalsystems/apalache-tests) are our acceptance tests. They take a lot of time. So it would be reasonable to run them on the weekend, before cutting a weekly release.

Perhaps an old-fashioned recipe, but why cannot we schedule it on a server with `cron`? The script would just run once a week and push the results of the experiments in git. The question is only, whether we like to periodically start and shutdown an aws instance, or do we need a standalone server for that.

**Comment by shonfeder** [comment] 2020-12-11 18:53
Sure, we can do that.  I think it reverses course from the work that was in process on that repo, but happy to revisit in January and figure out how we want to move forward.

**Comment by shonfeder** [comment] 2021-02-20 13:14
The scheduled running of this was closed by informalsystems/apalache-test#22

I've made an issue for part about integrating Informal specs.

**Closed by shonfeder** 2021-02-20 13:14 UTC
Labels: Alpha Centauri, CI/CD, FII1, testing
