### ISSUE TITLE
[BUG] Apalache produces non-deterministic counterexamples

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/apalache#814] opened 2021-05-07 12:32 UTC
## Description

The latest version of Apalache (v.0.15.4) produces non-deterministic counterexamples, both when run downloaded and via a Docker image.

## Input specification & command line parameters

When run from [this directory](https://github.com/informalsystems/tendermint-rs/tree/master/light-client/tests/support/model_based), with the only difference being `TestSuccessInv == ~TestSuccess` added to `LightTests.tla`, and the command

```
apalache-mc check --inv=TestSuccessInv --next=NextTest --init=InitTest MC4_4_faulty.tla
```
each of the produced counterexamples differs from previous ones.

## System information

- Apalache version: 0.15.4
- OS: Linux Mint
- JDK version: OpenJDK  11.0.9.1

Or, alternatively, the Docker image for v. 0.15.4 behaves in the same way.

## Additional context

This was supposed to be fixed in #318

**Comment by konnov** [comment] 2021-05-07 13:45
I am also getting various counterexamples. If you run `check --debug`, you will see that the SMT logs are identical. When I add `(get-model)` in the end of the log and replay the log with `z3 -smt2 log0.smt >out.txt`, I am also getting identical results.

**Comment by konnov** [comment] 2021-05-07 13:48
This is probably caused by non-determinism in the incremental solver. When I run Apalache in the "offline" mode, I am getting identical counterexamples:

```
apalache-mc check --inv=TestSuccessInv --next=NextTest --init=InitTest --algo=offline MC4_4_faulty.tla
```

**Comment by konnov** [comment] 2021-05-07 13:58
I am closing this issue for now, as we have a solution with the offline mode. If you find that the offline mode is non-deterministic too, feel free to reopen.

**Closed by konnov** 2021-05-07 13:58 UTC
Labels: bug
