### ISSUE TITLE
Confusing type error message

### ISSUE THREAD

**Issue by jtremback** [informalsystems/apalache#955] opened 2021-08-13 00:12 UTC
I received this error on my types:

`[ICS02.tla:7:5-7:21]: Need annotation. Found 2 matching operator signatures (((a749 -> a750), a749) => a750) or ((Seq(a749), Int) => a749) for arguments a747 and a748 E@17:10:12.873`

I can kind of guess what is going on here but obviously it is not that clear. I assume it's a pretty big task to make this any better than it is, but I thought I'd make an issue.

**Comment by shonfeder** [comment] 2021-08-13 00:18
Thanks for the report!

This is maybe a duplicate of #943, but that has an even broader scope, so we can keep this open as sub issue for now. It may be closed as a duplicate during triage.

**Comment by Kukovec** [comment] 2023-03-14 14:23
Closing this, we'll keep #943 for tracking error message UX.

**Closed by Kukovec** 2023-03-14 14:23 UTC
Labels: bug, FTC-Snowcat, usability, product-owner-triage
