### ISSUE TITLE
Employing Apalache for test case generation

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/apalache#2139] opened 2022-09-02 05:17 UTC
## Problem description

I am trying to use Apalache for test case generation, and have found that it behaves in an interesting way; would appreciate any help to improve my understanding.

Suppose I have the following (toy) spec, for which I want to generate test cases:

```tla
---- MODULE Test5 ----
EXTENDS Integers
VARIABLE
    \* @type: Int;
    x,
    \* @type: Int;
    y

Init == x = 0 /\ y = 0

Next == \/ x' = x + 1 /\ UNCHANGED <<y>> 
        \/ y' = y + 1 /\ UNCHANGED <<x>>

Sum5And2x == x + y >= 5 /\ x >=2
NotSum5And2x == ~Sum5And2x

Sum5And2y == x + y >= 5 /\ y >=2
NotSum5And2y == ~Sum5And2y

======================
```

So either `x` or `y` is incremented at each step, and I am interested in traces where the sum reaches 5, and either `x` or `y` is incremented at least twice.

I do it by running Apalache like this: `apalache check --inv=NotSum5And2x --max-error=10 Test5.tla`. I expect to get 10 different traces where `x` is implemented at least twice. Instead, I get 10 identical traces like this:

```tla
---------------------------- MODULE counterexample ----------------------------

EXTENDS Test5

(* Constant initialization state *)
ConstInit == TRUE

(* Initial state *)
State0 == x = 0 /\ y = 0

(* Transition 0 to State1 *)
State1 == x = 1 /\ y = 0

(* Transition 0 to State2 *)
State2 == x = 2 /\ y = 0

(* Transition 0 to State3 *)
State3 == x = 3 /\ y = 0

(* Transition 0 to State4 *)
State4 == x = 4 /\ y = 0

(* Transition 0 to State5 *)
State5 == x = 5 /\ y = 0

(* The following formula holds true in the last state and violates the invariant *)
InvariantViolation == x + y >= 5 /\ x >= 2

================================================================================
```

From `apalache check --inv=NotSum5And2y --max-error=10 Test5.tla` I get the traces that increment `y` twice, but also 10 identical ones:

```tla
---------------------------- MODULE counterexample ----------------------------

EXTENDS Test5

(* Constant initialization state *)
ConstInit == TRUE

(* Initial state *)
State0 == x = 0 /\ y = 0

(* Transition 0 to State1 *)
State1 == x = 1 /\ y = 0

(* Transition 1 to State2 *)
State2 == x = 1 /\ y = 1

(* Transition 1 to State3 *)
State3 == x = 1 /\ y = 2

(* Transition 1 to State4 *)
State4 == x = 1 /\ y = 3

(* Transition 0 to State5 *)
State5 == x = 2 /\ y = 3

(* The following formula holds true in the last state and violates the invariant *)
InvariantViolation == x + y >= 5 /\ y >= 2

================================================================================
```

I can try to use Apalache in simulation mode, like this `apalache simulate --length=5 --max-run=10 --output-traces Test5.tla`. This way I do get 10 different traces, but they are not constrained by the invariant, so I may get traces that do not increment `x` twice, for example; in other words I can't focus the search.

I can try to do invariant checking in simulation mode, like this: `apalache simulate --inv=NotSum5And2x --max-error=10 --length=5 --max-run=10 --output-traces Test5.tla`; but then after the first or second of generated example traces violate the invariant, simulation stops, and again 10 equivalent traces are produced, like this one:

```tla
---------------------------- MODULE counterexample ----------------------------

EXTENDS Test5

(* Constant initialization state *)
ConstInit == TRUE

(* Initial state *)
State0 == x = 0 /\ y = 0

(* Transition 1 to State1 *)
State1 == x = 0 /\ y = 1

(* Transition 1 to State2 *)
State2 == x = 0 /\ y = 2

(* Transition 0 to State3 *)
State3 == x = 1 /\ y = 2

(* Transition 1 to State4 *)
State4 == x = 1 /\ y = 3

(* Transition 0 to State5 *)
State5 == x = 2 /\ y = 3

(* The following formula holds true in the last state and violates the invariant *)
InvariantViolation == TRUE

================================================================================
```

Note that this trace is different than the one obtained via `apalache check`, because it was obtained via simulation first; but then it is again multiplied 10 times.

To summarize: I don't see the way how to currently employ Apalache for test case generation. Probably I am missing some options or configuration parameters?

## Desired solution

I would like to be able to do the following:
- When used in invariant checking mode, `apalache check --max-error=N` should produce `N` _different_ traces violating the invariant
- When used in simulation mode, `apalache simulate --inv=INV --max-error=N --max-run=M` should do `M` simulation runs even if invariant is violated. If it is violated for one of the simulated traces, then the model checker should try to produce `N` _different_ violating traces that are similar to the current violating trace. The important point is that `M` _different_ simulation traces should be produced in any case, violating the invariant or not.

I don't know whether the desired solution is feasible, only describing my ideal scenario. I would really appreciate your help here in either improving my understanding, or in bringing some enhancements to Apalache.

**Comment by thpani** [comment] 2022-09-02 07:10
Hi Andrey!

Apalache will produce different counter-examples under the hood in SMT, but their projection onto spec variables may be equivalent. You can manually define equivalence classes by giving the projection to exclude via `--view` to enumerate counterexamples ([Apalache manual](https://apalache.informal.systems/docs/apalache/principles/enumeration.html#enumerating-counterexamples)).

For your given spec, this could be as simple as

```tla
\* @type: <<Int>>;
View == << x >>
```

and

`apalache-mc check --inv=NotSum5And2x --max-error=10 --view=View Test5.tla`.

&nbsp;

Is this a feasible solution for your purposes, or do you need a more automated approach?

&nbsp;

Technical question for @konnov: Looks like `SeqModelChecker.excludePathView()` is currently a no-op if no view is provided. Is that intended?

**Comment by konnov** [comment] 2022-09-02 07:25
Correct. The first point is a duplicate of #1004.

> Technical question for @konnov: Looks like SeqModelChecker.excludePathView() is currently a no-op if no view is provided. Is that intended?

We've never implemented it, as it will most likely have very poor performance without a view. But in the @andrey-kuprianov's example it will definitely work fine. @thpani, would you like to try implementing #1004? It can be either implemented in `SeqModelChecker.excludePathView()` or by adding a default view in:

https://github.com/informalsystems/apalache/blob/b39ce05b2f8f51858d6ae5262fe5812a59e7ebaf/tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/VCGenerator.scala#L86-L108

**Comment by konnov** [comment] 2022-09-02 07:29
This one is probably also related: #1040

**Comment by konnov** [comment] 2022-09-02 07:36
> To summarize: I don't see the way how to currently employ Apalache for test case generation. Probably I am missing some options or configuration parameters?

As @thpani suggested, introduce:

```tla
\* requires a type annotation in this case, as <<Int, Int>> can either be a tuple, or a sequence
\* @type: <<Int, Int>>;
View == <<x, y>>
```

and run:

```sh
apalache-mc check --inv=NotSum5And2x --max-error=10 --view=View Test5.tla
```

We will see what can be done about #1004. However, the **default view will be a very suboptimal solution**.

**Comment by konnov** [comment] 2022-09-02 07:53
> I can try to use Apalache in simulation mode, like this apalache simulate --length=5 --max-run=10 --output-traces Test5.tla. This way I do get 10 different traces, but they are not constrained by the invariant, so I may get traces that do not increment x twice, for example; in other words I can't focus the search.

@andrey-kuprianov, note that this is the feature that lets you generating traces, when the user did not want to specify an invariant.

**Comment by konnov** [comment] 2022-09-02 08:03
> When used in simulation mode, apalache simulate --inv=INV --max-error=N --max-run=M should do M simulation runs even if invariant is violated. If it is violated for one of the simulated traces, then the model checker should try to produce N different violating traces that are similar to the current violating trace. The important point is that M different simulation traces should be produced in any case, violating the invariant or not.

I do not understand this point. Why do you need to perform `M` runs, if you have already found `N` errors? I think it would make sense to add another flag that limits the number of errors per run, so you could say produce 1000 errors in total, while each prefix generates 10 errors max. Most likely, nobody will get the meaning of these flags, so it has to be well hidden in the front-end tooling.

**Comment by konnov** [comment] 2022-09-02 09:03
CC from #1004:

> Actually, the command documentation says:
>
>> --view : the state view to use with --max-error=n, default: transition index
>
> Apparently, the transition index is not used by default.

This may be another option for the default exclusion behavior: Generate counterexamples that differ in transition indices.

**Comment by andrey-kuprianov** [comment] 2022-09-02 10:34
> I think it would make sense to add another flag that limits the number of errors per run, so you could say produce 1000 errors in total, while each prefix generates 10 errors max.

@konnov this also sounds like a nice option: to provide the global maximum, and then a local maximum for each case. This is actually what I want; we'll figure out the details later.

**Comment by andrey-kuprianov** [comment] 2022-09-02 10:48
@thpani, @konnov the suggestion about using Views is the right one, thanks! I of course new about them, but somehow forgot in this case...

Having some automation by default would be nice though... with either default views, defaulting to a tuple of all state variables, or simply to transition index, smth. like this; you know the technical details better, whatever makes more sense. 

From the MBT side, we will of course later employ smth. more advanced via the server mode to come. But for the end user, seeing 10 identical examples is confusing. Would be great to improve the experience of unexperienced users:)

**Comment by konnov** [comment] 2022-09-02 11:09
> > I think it would make sense to add another flag that limits the number of errors per run, so you could say produce 1000 errors in total, while each prefix generates 10 errors max.
> 
> @konnov this also sounds like a nice option: to provide the global maximum, and then a local maximum for each case. This is actually what I want; we'll figure out the details later.

Here is the relevant issue, we have to do some planning for it: #2143

**Comment by konnov** [comment] 2022-09-02 11:10
> From the MBT side, we will of course later employ smth. more advanced via the server mode to come. But for the end user, seeing 10 identical examples is confusing. Would be great to improve the experience of unexperienced users:)

We have the relevant discussion about inexperienced users: https://github.com/informalsystems/apalache/discussions/2142

**Closed** 2022-09-09 13:29 UTC
Labels: usability, user-support, feature, product-owner-triage
