### ISSUE TITLE
[BUG] cli `parse` command output is written to intermediate directory but not copied to output directory

### ISSUE THREAD

**Issue by danwt** [informalsystems/apalache#1072] opened 2021-11-03 19:22 UTC
Appears in _APALACHE version 0.17.0 build f62f370_

## Description

The command `apalache-mc parse --output=<filename> <tlafile>` does not actually write the output to $filename in the output directory. In fact, it actually writes the output to the intermediate directory, which is only visible if passing `--write-intermediate`.

## The command line parameters used to run the tool

`apalache-mc parse --output=<filename> <tlafile>` 

## Expected behavior

A file <filename> should be created in the output directory.

## System information

- Apalache version [`apalache-mc version`]: APALACHE version 0.17.0 build f62f370
- OS [e.g. Ubuntu Linux or Mac OS, and the current version]: OSX 11.5
- JDK version [e.g. OpenJDK 0.8.0]: OpenJDK Runtime Environment Zulu16.32+15-CA (build 16.0.2+7)

## Additional context

Reproduce with file main.tla

```
------------------------------------ MODULE main -----------------------------

\* @type: () => Bool;
Init ==
    /\ TRUE

Next == TRUE

===============================================================================
```

```
tree 3
.
├── apalache-pkg-0.17.0-full.jar
└── main.tla

java -jar apalache-pkg-0.17.0-full.jar parse --output=foobar.tla main.tla

tree 3
.
├── _apalache-out
│  └── main.tla_2021-11-03T19-20-28_10048578539153344840
│     ├── detailed.log
│     └── run.txt
├── apalache-pkg-0.17.0-full.jar
└── main.tla


java -jar apalache-pkg-0.17.0-full.jar --write-intermediate=true parse --output=foobar.tla main.tla

tree 4

.
├── _apalache-out
│  └── main.tla_2021-11-03T19-22-08_5579138356771785926
│     ├── detailed.log
│     ├── intermediate
│     │  ├── 00_OutParser.json
│     │  ├── 00_OutParser.tla
│     │  └── foobar.tla
│     └── run.txt
├── apalache-pkg-0.17.0-full.jar
└── main.tla
```

**Comment by shonfeder** [comment] 2021-11-03 19:45
If I'm not mistaken, this is all by design, following
 #1025.

**Comment by shonfeder** [comment] 2021-11-03 19:48
I did not mean to close this, especially not with such a curt message. Sorry!

To elaborate, iiuc:

- The parse output files are intermediate files.
- Those are only generated now when `--write-intermediate` is passed.
- All intermediate files are now written to the `intermediate` sub directory.

**Comment by danwt** [comment] 2021-11-03 19:51
> I did not mean to close this, especially not with such a curt message. Sorry!
> 
> To elaborate, iiuc:
> 
>     * The parse output files are intermediate files.
> 
>     * Those are only generated now when `--write-intermediate` is passed.
> 
>     * All intermediate files are now written to the `intermediate` sub directory.

Ah ok so it's true `parse` is mainly used internally but it is also exposed in the cli as a useful piece of functionality in of itself, so in that usage scenario it should probably be written to the output directory.

**Comment by shonfeder** [comment] 2021-11-03 19:54
Ah! I'm sorry! I misread! I read `output` as the new `out-dir` flag. I don't think this is be design, and it does seem like a new bug. Clearly the `output` flag is meant to specify the output file. My bad!

**Closed** 2021-11-04 10:53 UTC
Labels: bug
