### ISSUE TITLE
Deduplicate json deserialization

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#2226] opened 2022-10-17 14:04 UTC
With  #2201 in place we know have two sets of deserialization code for JSON -> TLA.

Creating this issue as a way to track the tech debt here.

FYI @Kukovec

**Comment by Kukovec** [comment] 2022-11-21 11:21
I will be closing this issue, and the associated PR, but I wanted to leave a record explaining why we won't be pursuing builder-based deserialization in the general case. Think of this as a mini ADR.

#2201 and #2207 kicked of a refactoring effort, meant to leverage the `ScopedBuilder`'s type guarantees when reading input from JSON files. This would have allowed us to skip the type-checking pass after reading in JSON input, as the IR would be type-correct-by-construction.
This all hinged on the idea that invoking the builder on JSON inputs _with proper type annotations_ (see #2223) would require a manageable amount of work and future maintenance. It turned out this assumption was incorrect.
I have spent several days working on this adaptation, and in my perspective the crux of the issue can be summarized as follows: input specifications may contain every conceivable syntactic structure, whereas the builder was designed to produce normal-form TLA+ (that is, the sort of TLA+ syntax one would find _after_ our preprocessing of arbitrary inputs).
Here are some concrete examples of syntax , which cannot be constructed with the builder on the current main branch:
  - `x / y`: TLA+ permits real division, Apalache and the builder don't support it
  - `\E <x,y> \in ...`, `\A <x,y> \in ...`: TLA+ allows for a sort of pattern matching of tuples. The builder requires that the quantified value be a single variable name
  - `{<x,y> \in S: P}`, `{e: <x,y> \in S}`: Same as above.
  - `[f EXCEPT ![a] = x]`: This gets parsed by SANY (and exported to/imported from JSON) as `[f EXCEPT ![<<a>>] = x]` even for single arguments, but gets type-annotated by the checker as `A -> B` (not `(A) -> B`!). This is a problem, because our type system treats `A -> B` and `(A) -> B` as different types (of functions), and the builder (correctly) constructs an expression with the type `(A) -> B`, which fails type validation against the present type-tag of `A -> B`.
  - `[f EXCEPT ![a] = x, ![b] = y]`: TLA+ has very permissive `EXCEPT` syntax, while the builder's `exceptMany` automatically constructs the nested form `[[f EXCEPT ![a] = x] EXCEPT ![b] = y]`.
  - `Gen(N)`: The builder expects a Scala `BigInt` argument, not a generic `Int`-typed expression (which may not inline to a literal)
  - `MkSeq(N, F(_))`: Same argument for `N` as above. Additionally, the builder expects all operators passed to methods which accept operators to be in call-by-name form, i.e. `LET A(...) == ... IN A`, not just correctly typed with an operator type (this is also true of e.g. folds).
  - most `ApalacheOper` expressions: The builder statically checks that the arguments to these operators have the correct shapes (e.g. `\E x \in S: P` for `skolem`), not just the correct types.

I've implemented ~13 new builder methods to support the generic input syntax, before determining that the implementation and maintenance burden just isn't worth it.
This is mainly because we can just use the same type-checker that we already use for `.tla` input, even though I'm reasonably confident that implementing a sufficiently extended builder is technically _possible_.

We will figure out what to do with `JsonToTlaViaBuilder` in the future, as it likely still has uses (as long as the provided json was produced _after_ preprocessing by Apalache, the builder import should require no, or aminimal number of, additional methods).

**Closed by Kukovec** 2022-11-21 11:21 UTC
Labels: refactoring
