### ISSUE TITLE
[FEATURE] Support for lambdas in folds or point to the known issues

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#1143] opened 2021-12-04 09:37 UTC
The [documentation on folds](https://apalache.informal.systems/docs/apalache/principles/folds.html#using-fold-operators-in-apalache) says that one is not allowed to use lambdas in folds.

```tla
--------------------------- MODULE FoldSetLambda ------------------------------ 
EXTENDS Integers, Apalache

VARIABLE
    \* @type: Int;
    sum

\* LAMBDAS in folds are not supported by Apalache
\* Define a LET-IN operator Plus(p,q) == p + q instead
X == FoldSet(LAMBDA p,q: p + q, 0, {1,2,3})

Init ==
    sum = X

Next ==
    sum' = sum
===============================================================================
```

The post-type checker reports a type error:

```
[FoldSetLambda.tla:10:14-10:30]: No annotation found for LAMBDA$1. Make sure that you've put one in front of LAMBDA$1.
```

However, the issue is not in the type checker. If we look at the output of the preprocessor, here is what we see:

In `04_OutUnroll.tla`:

```tla
(*
  @type: (() => Int);
*)
X ==
  FoldSet(LET (*
    @type: ((Int, Int) => Int);
  *)
  LAMBDA_si_1(p_si_1, q_si_1) == p$1 + q$1
  IN
  LAMBDA$1, 0, { 1, 2, 3 })

(*
  @type: (() => Bool);
*)
Init == sum = X
```

The types are perfectly fine.

In `05_OutInline.tla`:

```tla
(*
  @type: (() => Bool);
*)
Init == sum = FoldSet(LAMBDA$1, 0, { 1, 2, 3 })
```

So the issue is in the inlining, not the type checker. We should do one of the following:

  1. Fix the inliner to work correctly with folds and lambdas (why not?)
  2. If we do not want to fix the inliner, the tool should complain at the place where lambda is used and point to the known issues.

@Kukovec , what do you think?

**Comment by konnov** [comment] 2022-01-14 07:48
@Kukovec this is probably fixed, right?

**Comment by thpani** [comment] 2023-10-19 14:33
@Kukovec has this been fixed with the inliner work?

**Comment by Kukovec** [comment] 2023-10-19 14:38
IIRC the issue is that, while `LAMBDA ...` gets translated to a `LET ... IN ...`, it doesn't _always_ know what type annotation to attach, when the operator is polymorphic (unlike the + above). I'll see if I can get a nicer counterexample (or if the issue's gone away)

**Comment by Kukovec** [comment] 2023-10-19 14:48
So, if I change `X` to
```
X == ApaFoldSet(LAMBDA p,q: q, 0, {1,2,3}),
```
where the lambda is equivalent to
```
\* @type: (P,Q) => Q
Op(p, q) == q
```
The checker throws in BMC:
```
PASS #13: BoundedChecker                                          I@16:45:31.275
<unknown>: unexpected expression: Expected a non-polymorphic type, found: ((g, h) => h)
You may need to annotate an empty collection. E@16:45:31.283
test.tla:12:29-12:29: unexpected expression: Expected a non-polymorphic type, found: h
You may need to annotate an empty collection. E@16:45:31.284
```

**Comment by Kukovec** [comment] 2023-10-19 14:49
For non-polymorphic lambdas, there's no issue, since they just get translated to the commonly supported LET-IN.

**Comment by Kukovec** [comment] 2023-10-19 14:51
Note that there's still no way _to_ annotate a lambda, so the question is only whether we're happy with the error message here. The 2nd line `test.tla:12:29-12:29` identifies the `q` term in the lambda body accurately (though it might be worth looking into why the first line is `<unknown>:`, source tracking is broken here)

**Comment by thpani** [comment] 2023-10-20 12:39
Sounds fine, let's close this one

**Closed by thpani** 2023-10-20 12:39 UTC
Labels: usability, product-owner-triage
