### ISSUE TITLE
[FEATURE] Move `DeclarationSorter.explainCyclicDependency` to IO and use OutputManager

### ISSUE THREAD

**Issue by Kukovec** [informalsystems/apalache#1039] opened 2021-10-13 11:33 UTC
The method produces output files (`dependencies.dot`) so it should not be in `lir`, but in `io`. Additionally, the output location should be managed by `OutputManager` (#1036).

**Comment by thpani** [comment] 2023-10-19 14:20
Duplicate of #1039

**Closed by thpani** 2023-10-19 14:20 UTC
Labels: refactoring
